services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: payload
      POSTGRES_PASSWORD: payload
      POSTGRES_DB: mardini_cms
    volumes:
      - payload_pg_data:/var/lib/postgresql/data

volumes:
  payload_pg_data:
